name:                haskell-scripted-wai
version:             0.1.0.0
github:              "githubuser/haskell-scripted-wai"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-scripted-wai#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- wai
- warp
- containers
- scotty # Contains wai, wai-extra, warp
- hspec
- hspec-wai
- hs-duktape
- text
# I can't fucking figure out how to convert between
# Data.Internal.Lazy.Text and String -- so here goes another dep
- text-conversions
- bytestring

library:
  source-dirs: src

executables:
  haskell-scripted-wai-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # Custom
    - -Wall
    dependencies:
    - haskell-scripted-wai

tests:
  haskell-scripted-wai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # Custom
    - -Wall
    dependencies:
    - haskell-scripted-wai
